server:
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/road?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: rlaehrud9919@

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s

upload:
  dir: ${upload}